apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
configMapGenerator:
  - name: php-scripts
    files:
      - ../airflow-dags/php-scripts/my_job.php

generatorOptions:
  disableNameSuffixHash: true